# Generated by Django 4.1.3 on 2022-11-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('user_rid', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_mobile', models.CharField(max_length=10, null=True)),
                ('user_created_datetime', models.DateTimeField()),
                ('user_modified_datetime', models.DateTimeField(null=True)),
                ('user_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
