# Generated by Django 4.1.3 on 2022-11-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('task_rid', models.IntegerField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=255)),
                ('task_description', models.TextField(null=True)),
                ('task_created_datetime', models.DateTimeField()),
                ('task_mod_datetime', models.DateTimeField(null=True)),
                ('task_status', models.IntegerField(default=0)),
                ('task_user_rid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.usersmodel')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
